name: flutter_firebase_uber
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fdottedline_nullsafety: ^2.0.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  google_maps_flutter: ^2.1.0
  lottie: ^1.2.1
  pin_code_fields: ^7.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Medium.otf
        - asset: assets/fonts/AvenirLTStd-Book.otf
          style: italic

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - .env
    - assets/animations/
    - assets/images/
    - assets/maps/
    - assets/fonts/
